import { Inter } from "next/font/google";
import "./globals.css";
import LandinPageSection1 from "../app/landingPage/landingPageSection1";
import LandinPageSection2 from "../app/landingPage/landingPageSection2";
import LandinPageSection3 from "../app/landingPage/landingPageSection3";
import LandinPageSection4 from "../app/landingPage/landingPageSection4";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LandinPageSection1 />
        <LandinPageSection2 />
        <LandinPageSection3 />
        <LandinPageSection4 />
        <Footer />

        {children}
      </body>
    </html>
  );
}
